### ISSUE TITLE
Rate Limiting Error

### ISSUE THREAD

**Issue by SamTyurenkov** [huecker-io/huecker#8]
### Description

I tried to pull phpmyadmin base image directly and faced a 500 error:

```
=> ERROR [phpmyadmin internal] load metadata for huecker.io/library/phpmyadmin:5.2.1                                                                                                                                                               1.4s
------
 > [phpmyadmin internal] load metadata for huecker.io/library/phpmyadmin:5.2.1:
------
failed to solve: huecker.io/library/phpmyadmin:5.2.1: failed to resolve source metadata for huecker.io/library/phpmyadmin:5.2.1: unexpected status from HEAD request to https://huecker.io/v2/library/phpmyadmin/manifests/5.2.1: 500 Internal Server Error
```

If i proceed to the mentioned in error manifest page https://huecker.io/v2/library/phpmyadmin/manifests/5.2.1 it results in the following error:

```
{"errors":[{"code":"UNKNOWN","message":"unknown error","detail":"toomanyrequests: You have reached your unauthenticated pull rate limit. https://www.docker.com/increase-rate-limit"}]}
```

### Reproduce

I used this Dockerfile and passed huecker.io/library as CUSTOM_REGISTRY:

```
# Define the build argument for the custom registry domain
ARG CUSTOM_REGISTRY

# Default base image (from Docker Hub)
ARG BASE_IMAGE="phpmyadmin:5.2.1"

# Construct the fully qualified image name
ARG FULL_IMAGE_NAME="${CUSTOM_REGISTRY:+${CUSTOM_REGISTRY}/}${BASE_IMAGE}"

# Use the constructed image name in the FROM instruction
FROM ${FULL_IMAGE_NAME}
```

With this command i trigger a build stage for that service:
`env USER_ID=${USER_ID} env GROUP_ID=${GROUP_ID} docker-compose up -d --force-recreate --build phpmyadmin`

And the service itself is described in docker-compose.yml:
```
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin-custom:latest
    container_name: phpmyadmin
    build:
      context: docker/phpmyadmin/
      args:
        CUSTOM_REGISTRY: ${CUSTOM_REGISTRY}
    restart: always
    environment:
      - PMA_ARBITRARY=0
      - PMA_ABSOLUTE_URI=http://${SITE_DOMAIN}/${DB_ADMIN_WEBPATH}/
      - PMA_HOST=db
      - UPLOAD_LIMIT=300M
      - PMA_PORT=3306
    expose:
      - '80'
    networks:
      - wpbox-network
```

### Expected behavior

The base image manifest is accessed and image is pulled, maybe cache manifest on your side to avoid rate limiting?

### registry version

I dont think i used that.
